### ISSUE TITLE
InferOptions and friends are not exported

### ISSUE THREAD

**Issue by koterpillar** [commander-js/extra-typings#32]
My program has wrapper objects for different `Command`s and I'm trying to type them appropriately. However, I can't write the necessary types because `InferOptions` and associated types aren't exported. I.e.

```typescript
class Wrapper<Args, Opts> {
  constructor(private readonly cmd: Command<Args, Opts>) {}

  public specialOption(): Wrapper<Args, ???> { // Can't use InferOptions<Opts, ...> here
    return new Wrapper(this.cmd.option("--special"));
  }
}

**Comment by shadowspawn** [comment]
I don't quite understand the usage pattern. This compiles, but may not be heading in the right direction for your wrapper:

```typescript
class Wrapper<Args extends any[], Opts extends OptionValues> {
  cmd: Command<Args, Opts>;

  constructor(private readonly cmdArg: Command<Args, Opts>) {
    this.cmd = cmdArg;
  }

  public static specialOption() {
    return new Wrapper(new Command().option("--special"));
  }
}

const w = Wrapper.specialOption();
```

**Comment by koterpillar** [comment]
What I'm trying to do is to build a CLI with several subcommands, so I want to provide some shortcuts like `specialOption` for commonly used options. I could have inherited `Wrapper` from `Command` but there are warnings against that, so I chose to have `Command` as a member instead.

How do I write the return type for `specialOption` in this example?

**Comment by shadowspawn** [comment]
My feeling is any manual use of `InferOptions` is going to be messy.

Try just removing the return type, and let TypeScript do the heavy lifting. (`inner` is just for inspecting the inferred type, not part of the solution as such.)

```typescript
// wrapper.ts
import { Command, OptionValues } from '@commander-js/extra-typings';

export class Wrapper<Args extends any[], Opts extends OptionValues> {
  constructor(private readonly cmd: Command<Args, Opts>) {
  }

  public specialOption() {
    return new Wrapper(this.cmd.option("--special"));
  }

  public inner() {
    return this.cmd;
  }
}
```

```typescript
// call-wrapper.ts
import { Command } from '@commander-js/extra-typings';
import { Wrapper } from './wrapper.js';

const w = new Wrapper(new Command())
  .specialOption();

const ok = w.inner().opts().special;
const error = w.inner().opts().unknown;
```

**Comment by koterpillar** [comment]
I am finding more awkwardness in what I tried to do and not a lot of benefit so going to close this.

**Comment by shadowspawn** [comment]
Added in v14.0.0: export InferArgument, InferArguments, InferCommandArguments, and InferOptions
