### ISSUE TITLE
Missing type for `Command.options`

### ISSUE THREAD

**Issue by cj-christoph-gysin** [commander-js/extra-typings#46]
[`Command` has a property `options`](https://github.com/tj/commander.js/blob/master/typings/index.d.ts#L283) which [seems to be missing in this repo](https://github.com/commander-js/extra-typings/blob/main/index.d.ts#L456-L457).

**Comment by shadowspawn** [comment]
Yes, thanks for report.

Have have not caught up with these changes: https://github.com/tj/commander.js/pull/1827

**Comment by shadowspawn** [comment]
Added in v11.1.0
