### ISSUE TITLE
Number parsing

### ISSUE THREAD

**Issue by Zamiell** [commander-js/extra-typings#51]
Hello, and thanks for the library.

One problem with this library is that all of the options seem to be strings. Can you show an example in the README of how to use an option that is a number?

e.g.

```ts
const command = new Command()
  .command("init")
  .addOption(
    new Option(
      "-s, --slot <slot>",
      "The slot that you want to use.",
    ).choices(["1", "2", "3"]),
  )

const opts = command.opts();
console.log(typeof opt.slot); // "string" instead of "number"
```

**Comment by shadowspawn** [comment]
This library is extra types on top of [Commander](https://github.com/tj/commander.js), and Commander has an extensive README covering usage. Have a look at the [Custom option processing](https://github.com/tj/commander.js#custom-option-processing) section and the `myParseInt` example.

**Comment by Zamiell** [comment]
Hi shadowspawn,

Thank you for the quick reply. The section that you linked only shows how to use validator functions with the "option" method. But in my example in the OP, I am using the "addOption" method, which is different. The "Option" class constructor does not take a third argument, at least according to TypeScript. Can you clarify exactly how to use a validator function with the "addOption" method, completing the code snippet in the OP?

**Comment by shadowspawn** [comment]
There is coverage in the Options [More configuration](https://github.com/tj/commander.js#more-configuration) section. Basically, there are methods corresponding to the `.option()` arguments, such as `.default()` and `.argParser()`.

There is a problem with your example though, `.choices()` is implemented using a custom parser so you can't use both `choices` and your own custom parser.

**Comment by Zamiell** [comment]
> .choices() is implemented using a custom parser so you can't use both choices and your own custom parser.

Ah, that was the confusing part for me, thank you.

For future readers, here is the working code:

```ts
const command = new Command()
  .command("init")
  .option(
    "-s, --slot <slot>",
    "The slot that you want to use.",
    validateSlot,
    1,
  )

function validateSlot(valueString: string): number {
  const valueNumber = parseIntSafe(valueString);
  if (valueNumber === undefined) {
    throw new InvalidOptionArgumentError(
      `The slot of "${valueString}" is not a number.`,
    );
  }

  if (valueNumber !== 1 && valueNumber !== 2 && valueNumber !== 3) {
    throw new InvalidOptionArgumentError(
      "The slot must be equal to 1, 2, or 3.",
    );
  }

  return valueNumber;
}

const opts = command.opts();
console.log(typeof opt.slot); // is "number" at run-time (and is number at compile-time in TypeScript too!)
```

**Comment by Zamiell** [comment]
I will say that having number arguments is an extremely common pattern. I think it makes sense to force users to roll their own validation function when they want to validate the option being both a number and a number restricted to a certain range. However, forcing users to roll their own validation function when they just want the option to be a number seems a bit verbose, so I think there is room for improvement here. Maybe this library could expose some way as marking that "this option should be a number instead of a string"?

**Comment by shadowspawn** [comment]
Originally the author could simply pass `parseInt` as a coercion function so ints were easy, but that broke when the "accumulator" functionality got added to the custom parsing. This was a common issue until the documentation caught up and improved: [#943
](https://github.com/tj/commander.js/issues/943)

You can still use `parseFloat` as a simple conversion function.

> However, forcing users to roll their own validation function when they just want the option to be a number seems a bit verbose, so I think there is room for improvement here. Maybe this library could expose some way to mark that "this option should be a int instead of a string"?

Sticking with the current API, I have wondered about supplying some conversion functions, but felt it would also be somewhat verbose.

**Comment by Zamiell** [comment]
I'll close the issue for now, thank you.
