### ISSUE TITLE
Gradual typing

### ISSUE THREAD

**Issue by ikonst** [commander-js/extra-typings#64]
Any recommendations for how you can integrate this package into your script gradually, i.e. when you have a command composed of many sub-commands and you only migrate some of them?

**Comment by shadowspawn** [comment]
You could do a type coercion to migrate a command. A couple of examples, doing a coercion to make a strongly typed alias for the program, or typing a single command at a time.

```ts
import { Command } from 'commander';
import { Command as TsCommand } from '@commander-js/extra-typings';

const program = new Command();
const tsProgram = program as TsCommand;

(program as TsCommand).command('print')
   .option('-c, --colour')
   .argument('<file>')
   .action((file, options) => {
      // typed file and options
      console.log(`print ${file} with colour ${options.colour}`);
   });

tsProgram.command('compress')
   .option('-l, --level <0-6>')
   .argument('<file>')
   .action((file, options) => {
      // typed file and options
      console.log(`compress ${file} with level ${options.level}`);
   });

program.parse();
```

**Comment by ikonst** [comment]
I found that `Command` and `TsCommand` were incompatible so I had to "cast" through an `as unknown as TsCommand`.

**Comment by shadowspawn** [comment]
That is a pity, nicer when TypeScript agrees the coercion is reasonable. Might be a TypeScript version or configuration difference. I used TypeScript 5.4.2 and `tsconfig.json` created with `tsc --init` for the sample code with the one-step cast.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
