### ISSUE TITLE
How may I type "external" functions?

### ISSUE THREAD

**Issue by TheAyes** [commander-js/extra-typings#68]
Hello!

I have a quick question. I'd like to extract my command actions into functions in seperate files. but I don't receive any typed parameters. Now I wonder how I should type them out?

```ts
const runTestAction = (file) => {
  //...
}

program
  .command("test <file>")
  .action(runTestAction)
```

**Comment by shadowspawn** [comment]
The usual way I do this is type the external handlers myself, and then get the type checking against the Commander derived types when adding them to the action handler.

It might be possible to export some types from the program definition, but going to be circular with then importing the external handler defined using that type...

**Comment by TheAyes** [comment]
Ah. Well I might just stick to the anonymus action function then. Perhaps I can switch once I'm certain the definitions won't change every second commit.
