### ISSUE TITLE
Global options aren't being recognized

### ISSUE THREAD

**Issue by TheAyes** [commander-js/extra-typings#69]
Hi!

My "global" options aren't being picked up by your typing system.

I have nested commands and the typing system only recognizes current level options.

```ts
export const projects = new Command("projects")
  .option("--dry")
  .option("--verbose");

projects
  .command("add")
  .argument("<project>")
  .action((projectPath, options) => {
    console.log(options.dry); // TS2339: Property dry does not exist on type {}
  });
```

**Comment by TheAyes** [comment]
So for now I'Ve worked around it like this:

```ts
import { Command } from "@commander-js/extra-typings";

export const makeProjectCommand = () => {
	const projects = new Command("projects")
		.option("--dry")
		.option("--verbose");

	type GlobalOptionType = ReturnType<typeof projects.opts>;

	projects
		.command("add")
		.argument("<project>")
		.action((projectPath, localOptions) => {
			type IntersectedOptions = GlobalOptionType & typeof localOptions;
			const options = localOptions as IntersectedOptions;

			options.dry;
		});

	projects.command("remove").action(() => {});

	return projects;
};
```

It's still kinda meh, but atleast I won't get type warnings like this.

**Comment by shadowspawn** [comment]
The warning about `options.dry` in your example is correct. The `--dry` option of the root command is stored on the root command and not on the `add` command (and not passed in with the `options` parameter to the `add` action handler).

You can either access the options on the root command directly, or using `.optsWithGlobals()` in a leaf command (but it is not strongly typed).

```js
projects
  .command("add")
  .option('--local')
  .argument("<project>")
  .action((projectPath, options, cmd) => {
    console.log(options);
    console.log(projects.opts());
    console.log(cmd.optsWithGlobals());
  });
```

**Comment by TheAyes** [comment]
I see.

I guess I thought of the options as a "global" object sort of and the further down I go in the command chain the more options it inherits. 

This answers my question :) Much appreciated.

**Comment by shadowspawn** [comment]
> You can either access the options on the root command directly, or using `.optsWithGlobals()` in a leaf command (but it is not strongly typed).

For interest, PR to make `.optsWithGlobals()` strongly typed: #78
