### ISSUE TITLE
add utility type `InferOptions`

### ISSUE THREAD

**Issue by matthyk** [commander-js/extra-typings#73]
Currently, the type of the options of a command can only be obtained by calling the opts method. However, it would be useful if the type could be extracted independently of this so that it could be used in other places, for example.

# Example

```ts
program.addOption(new Option('-v, --verbose'))

type Options = InferOptionsFromCommand<typeof program>
/*
type Options = {
  verbose?: boolean
}
*/
```

Another useful utility would be the possibility to automatically extract the type from an object that is filled with options. This is particularly useful if you store options in objects for reuse. Again for a brief example.

# Example
```ts
const options = {
  level: new Option('-l, --level').choices(['trace', 'debug', 'info', 'warn', 'error', 'fatal']).default('info'),
  verbose: new Option('-v, --verbose')
}

// new `InferOptions` type
type Options = InferOptions<typeof options>
/*
type Options = {
  level: 'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal',
  verbose?: boolean
}
*/

```

**Comment by shadowspawn** [comment]
There is a TypeScript support for getting the type of a method. So for the first example:

```ts
const program = new Command().addOption(new Option('-v, --verbose'))

type OptionsType = ReturnType<typeof program['opts']>;
```

**Comment by shadowspawn** [comment]
> However, it would be useful if the type could be extracted independently of this so that it could be used in other places, for example.

This does not require much code using a direct TypeScript approach (https://github.com/commander-js/extra-typings/issues/73#issuecomment-2323491638) instead of defining and advertising a custom utility type. 

I am not against the idea though, if it proves more popular in future.

> Another useful utility would be the possibility to automatically extract the type from an object that is filled with options.

I think that is a bit too special case to add.
